blank_issues_enabled: true
contact_links:
  - name: Ladybird upstream Discord
    url: https://discord.gg/nvfjVJ4Svh
    about: Chat with Ladybird upstream maintainers and contributors.
  - name: Ladybird upstream FAQ
    url: https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/FAQ.md
    about: Read the Ladybird upstream FAQ.
  - name: Ladybird upstream documentation
    url: https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/README.md
    about: Read Ladybird upstream build and development documentation.
  - name: Ladybird upstream contribution guidelines
    url: https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md
    about: Read the Ladybird upstream participation guidelines.
